# Site settings
title: Map Tech & Code
email: david.raleigh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Technical Blog Posts and Tutorials for Programmers in Mapping and GIS
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://davidraleigh.github.io/" # the base hostname & protocol for your site
twitter_username: fogmodel
github_username:  davidraleigh

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

gems:
  - jekyll-seo-tag
  
